### ISSUE TITLE
User removed from groups

### ISSUE THREAD

**Issue by jayaich** [vbalazs/mediawiki-shibboleth-authentication#6]
Hello,

It seems that the ShibAddGroups function initially removes the user from his/her groups. However, at no point does it re-add those groups, and it takes no account of the fact that perhaps no extra groups have been set. This can be seen by the fact that being in the 'administrator' and 'bureaucrat' groups, once I have logged in I am no longer in those groups.

The fix is to return from the function immediately unless '$shib_groups' is set (the patch line numbering is probably out, so check carefully):

@@ -470,6 +473,9 @@
        global $shib_groups;
        global $shib_group_prefix;
 
+       if ($shib_groups === null)
+               return;
+
        $oldGroups = $user->getGroups();
         foreach ($oldGroups as $group) {
                 $user->removeGroup($group);

**Comment by vbalazs** [comment]
solved with #8
